title: AI Deadlines 

description: Countdowns to top ML / CV / MIC conference and special call deadlines
author: YANG Jiancheng
maintainers: duducheng

domain: "creedai.github.io/ai-deadlines/"
baseurl: ""

github_username: creedai
github_repo: ai-deadlines

markdown: kramdown
