title: AI Deadlines
remark: CV-oriented

description: Countdowns to top ML / CV / MIC conference and special issue deadlines
author: YANG Jiancheng
maintainers: duducheng

domain: "creedai.github.io/ai-deadlines/"
baseurl: "ai-deadlines"

github_username: creedai
github_repo: ai-deadlines

markdown: kramdown
